version: '3.8'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"

volumes:
  jenkins_home:
