
Prompt ============================================================================
Prompt Creating/Upgrading Team Coding objects
Prompt ============================================================================
DEFINE OWNER = 'HR'
DEFINE tablespace_info = ' '
DEFINE tablespace_ind_info = ' '
DEFINE TC_ADMIN =TC_ADMIN_ROLE
Prompt Creating Role TC_ADMIN_ROLE
CREATE ROLE TC_ADMIN_ROLE;
Prompt Granting Role TC_ADMIN_ROLE to User HR
GRANT TC_ADMIN_ROLE TO HR with ADMIN OPTION;


/* Team Coding Main Configuration Table */
CREATE TABLE &&OWNER..TCX_CONFIG
( CONFIG_ID           INTEGER                   NOT NULL,
  CONFIG_DESCRIPTION  VARCHAR2(255 BYTE)        NOT NULL,
  CONFIG_TIMESTAMP    DATE,
  OBJECT_TIMESTAMP    DATE,
  DBID                NUMBER,
  DBNAME              VARCHAR2(255),
  STATUS              CHAR(1)                   NOT NULL CHECK (STATUS IN ('A','I','D','F','O','U')),
  STATUS_TYPE         VARCHAR2(30 BYTE),
  STATUS_BY           VARCHAR2(128 BYTE)        NOT NULL,
  STATUS_TIMESTAMP    DATE                      NOT NULL,
  ENFORCE_DBLOCKS     CHAR(1) DEFAULT 'N'       NOT NULL CHECK (ENFORCE_DBLOCKS IN ('Y','N')) ,
  TC_OBJ_STORE        CLOB,
  COMMENTS            VARCHAR2(255 BYTE),
  constraint tcx_config_pk
    primary key (CONFIG_ID)
    using index &&tablespace_ind_info)
   &&tablespace_info;

Prompt Creating index TCX_CONFIG_DESC_NDX
CREATE UNIQUE index &&OWNER..TCX_CONFIG_DESC_NDX
    on &&OWNER..TCX_CONFIG (CONFIG_DESCRIPTION)
    &&tablespace_ind_info;

/* Team Coding Projects Table */
CREATE TABLE &&OWNER..TCX_TEAM_PROJECTS
( CONFIG_ID             INTEGER            NOT NULL,
  PROJECT_ID            INTEGER            NOT NULL,
  TEAM_PROJECT          VARCHAR2(255 BYTE) NOT NULL,
  VCS_PROVIDER          VARCHAR2(255 BYTE),
  VCS_PROJECT           VARCHAR2(2000 BYTE),
  STATUS                CHAR(1)            NOT NULL CHECK (STATUS IN ('A','I','D','F','O','U')),
  STATUS_TYPE           VARCHAR2(30 BYTE),
  STATUS_BY             VARCHAR2(128 BYTE) NOT NULL,
  STATUS_TIMESTAMP      DATE               NOT NULL,
  COMMENTS              VARCHAR(255 BYTE),
  PROJECT_CONFIGURATION CLOB,
  constraint tcx_team_projects_pk
    primary key (CONFIG_ID, PROJECT_ID)
    using index &&tablespace_ind_info )
    &&tablespace_info;

Prompt Adding foreign key constraint TCX_TEAM_PROJ_CONFIG_FK
ALTER TABLE &&OWNER..TCX_TEAM_PROJECTS ADD (
  CONSTRAINT TCX_TEAM_PROJ_CONFIG_FK
  FOREIGN KEY (CONFIG_ID)
  REFERENCES &&OWNER..TCX_CONFIG (CONFIG_ID));

Prompt Creating index TCX_TEAM_PROJECTS_NDX
CREATE UNIQUE index &&OWNER..TCX_TEAM_PROJECTS_NDX
  on &&OWNER..TCX_TEAM_PROJECTS (TEAM_PROJECT)
  &&tablespace_ind_info;

 /* Team Coding Objects Table */
CREATE TABLE &&OWNER..TCX_OBJECTS
( CONFIG_ID                   INTEGER             NOT NULL,
  PROJECT_ID                  INTEGER             NOT NULL,
  OBJECT_ID                   INTEGER             NOT NULL,
  OBJECT_TYPE                 VARCHAR2(30 BYTE)   NOT NULL,
  OBJECT_OWNER                VARCHAR2(128 BYTE)  NOT NULL,
  OBJECT_NAME                 VARCHAR2(128 BYTE)  NOT NULL,
  OBJECT_SOURCE_FILENAME      VARCHAR2(300 BYTE)  NOT NULL,
  VCS_PROJECT                 VARCHAR2(2000 BYTE),
  TEAM_PROJECT                VARCHAR2(255 BYTE)  NOT NULL,
  VCS_SOURCE_FILENAME         VARCHAR2(2000 BYTE) NOT NULL,
  NUMBER_OF_LOCKS             INTEGER             NOT NULL CHECK (NUMBER_OF_LOCKS >= 0),
  EXCLUSIVE_LOCK              CHAR(1)             NOT NULL CHECK (EXCLUSIVE_LOCK IN ('Y','N')),
  LAST_CHECKOUT_DBUSER        VARCHAR2(128 BYTE),
  LAST_CHECKOUT_VCSUSER       VARCHAR2(128 BYTE),
  LAST_CHECKOUT_OSUSER        VARCHAR2(128 BYTE),
  LAST_CHECKOUT_TIMESTAMP     DATE,
  LAST_CHECKOUT_VCS_REVISION  VARCHAR2(30 BYTE),
  LAST_CHECKOUT_TC_REVISION   VARCHAR2(30 BYTE)   NOT NULL ,
  LAST_CHECKOUT_COMMENTS      VARCHAR2(200 BYTE),
  LAST_CHECKIN_DBUSER         VARCHAR2(128 BYTE),
  LAST_CHECKIN_VCSUSER        VARCHAR2(128 BYTE),
  LAST_CHECKIN_OSUSER         VARCHAR2(128 BYTE),
  LAST_CHECKIN_VCS_REVISION   VARCHAR2(30 BYTE),
  LAST_CHECKIN_TC_REVISION    VARCHAR2(30 BYTE)   NOT NULL ,
  LAST_CHECKIN_TIMESTAMP      DATE,
  LAST_CHECKIN_COMMENTS       VARCHAR2(200 BYTE),
  STATUS                      CHAR(1)             NOT NULL CHECK (STATUS IN ('A','I','D','F','O','U')),
  STATUS_TYPE                 VARCHAR2(30 BYTE),
  STATUS_BY                   VARCHAR2(128 BYTE)  NOT NULL,
  STATUS_TIMESTAMP            DATE                NOT NULL,
  OBJECT_ATTTRIBUTES          CLOB,
  COMMENTS                    VARCHAR2(255 BYTE),
  constraint tcx_objects_pk
    primary key (CONFIG_ID, PROJECT_ID, OBJECT_ID)
    using index &&tablespace_ind_info)
   &&tablespace_info;

Prompt Adding foreign key constraint TCX_TC_OBJ_TEAM_PROJ_FK
ALTER TABLE &&OWNER..TCX_OBJECTS ADD (
  CONSTRAINT TCX_TC_OBJ_TEAM_PROJ_FK
  FOREIGN KEY (CONFIG_ID, PROJECT_ID)
  REFERENCES &&OWNER..TCX_TEAM_PROJECTS (CONFIG_ID, PROJECT_ID));

Prompt Creating index TCX_OBJECTS_NDX
CREATE UNIQUE index &&OWNER..TCX_OBJECTS_NDX
  on &&OWNER..TCX_OBJECTS (CONFIG_ID, PROJECT_ID, OBJECT_TYPE, OBJECT_OWNER, OBJECT_NAME)
  &&tablespace_ind_info;

/* Team Coding Objects History Table */
CREATE TABLE &&OWNER..TCX_OBJECT_HISTORY
( CONFIG_ID           INTEGER                   NOT NULL,
  PROJECT_ID          INTEGER                   NOT NULL,
  OBJECT_ID           INTEGER                   NOT NULL,
  TRANSACTION_ID      INTEGER                   NOT NULL,
  TRANSACTION_TYPE    VARCHAR2(30 BYTE)         NOT NULL,
  TC_ACTION           VARCHAR2(30 BYTE)         NOT NULL,
  TC_REVISION         VARCHAR2(30 BYTE)         NOT NULL,
  VCS_REVISION        VARCHAR2(30 BYTE),
  VCS_PROVIDER        VARCHAR2(255 BYTE),
  VCPID               INTEGER,
  VCS_PROJECT         VARCHAR2(2000 BYTE),
  DB_USER             VARCHAR2(128 BYTE),
  VCS_USER            VARCHAR2(128 BYTE),
  OS_USER             VARCHAR2(128 BYTE),
  CHECKOUT_TIMESTAMP  DATE,
  CHECKIN_TIMESTAMP   DATE,
  TRANSACTION_TIMESTAMP DATE                    NOT NULL,
  CX_RUNNAME          VARCHAR2(100 BYTE),
  COMPLETED           CHAR(1) DEFAULT 'N'      NOT NULL CHECK ( COMPLETED IN ('Y','N')),
  COMMENTS            VARCHAR2(255 BYTE),
  SYS_COMMENTS        VARCHAR2(255 BYTE),
  constraint tcx_object_hist_pk
    primary key (CONFIG_ID, PROJECT_ID,OBJECT_ID,TRANSACTION_ID)
    using index &&tablespace_ind_info)
   &&tablespace_info;

Prompt Adding foreign key constraint TCX_TC_OBJ_TEAM_PROJ_FK
ALTER TABLE &&OWNER..TCX_OBJECT_HISTORY ADD (
  CONSTRAINT TCX_OBJHIST_OBJ_PROJ_FK
  FOREIGN KEY (CONFIG_ID, PROJECT_ID, OBJECT_ID)
  REFERENCES &&OWNER..TCX_OBJECTS (CONFIG_ID, PROJECT_ID, OBJECT_ID));

/* ID Trigger/Sequence combinations */

/* TCX_CONFIG */
-- Sequence
CREATE SEQUENCE &&OWNER..TCX_CONFIG_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE OR REPLACE TRIGGER &&OWNER..TCX_CONFIG_TRG
BEFORE INSERT
ON &&OWNER..TCX_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
  Select &&OWNER..TCX_CONFIG_SEQ.nextval into n from dual;
  :new.CONFIG_ID := N;
END TCX_CONFIG_TRG;
/

/* TCX_TEAM_PROJECTS */
-- Sequence
CREATE SEQUENCE &&OWNER..TCX_TEAM_PROJECTS_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE OR REPLACE TRIGGER &&OWNER..TCX_TEAM_PROJECTS_TRG
BEFORE INSERT
ON &&OWNER..TCX_TEAM_PROJECTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
  Select &&OWNER..TCX_TEAM_PROJECTS_SEQ.nextval into n from dual;
  :new.PROJECT_ID := N;
END TCX_TEAM_PROJECTS_TRG;
/

/*TCX OBJECTS */
-- Sequence for adding SCRIPTS to TCX_OBJECTS table. DB OBJECTS OBJECT_ID is from ORACLE OBJECT_ID
CREATE SEQUENCE &&OWNER..TCX_SCRIPT_SEQ
  INCREMENT BY -1
  MAXVALUE -10
  MINVALUE -2147483648
  NOCYCLE
  CACHE 20
  NOORDER;

/*TCX OBJECT_HISTORY */
-- Sequence
CREATE SEQUENCE &&OWNER..TCX_OBJECT_HISTORY_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER &&OWNER..TCX_OBJECT_HISTORY_TRG
BEFORE INSERT
ON &&OWNER..TCX_OBJECT_HISTORY
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
-- For Toad:  Highlight column TRANSACTION_ID
  Select &&OWNER..TCX_OBJECT_HISTORY_SEQ.nextval into n from dual;
  :new.TRANSACTION_ID := N;
END TCX_OBJECT_HISTORY_TRG;
/

/* Update Triggers */
Prompt Creating trigger TCX_CONFIG_TIMESTAMP_TRG
create or replace
  TRIGGER &&OWNER..TCX_CONFIG_TIMESTAMP_TRG
    BEFORE INSERT
       OR UPDATE
    ON &&OWNER..TCX_CONFIG
    FOR EACH ROW
    BEGIN
      :NEW.CONFIG_TIMESTAMP := SYSDATE;
END;
/

Prompt Creating trigger TCX_UPD_OBJ_TIMESTAMP
CREATE OR REPLACE TRIGGER &&OWNER..TCX_UPD_OBJ_TIMESTAMP
  AFTER INSERT OR DELETE OR UPDATE
  ON &&OWNER..TCX_OBJECTS
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  UPDATE &&OWNER..TCX_CONFIG
     SET OBJECT_TIMESTAMP = SYSDATE
   WHERE CONFIG_ID = :NEW.CONFIG_ID;
END;
/

Prompt Creating trigger TCX_UPD_PROJ_TIMESTAMP
CREATE OR REPLACE TRIGGER &&OWNER..TCX_UPD_PROJ_TIMESTAMP
  AFTER INSERT OR DELETE OR UPDATE
  ON &&OWNER..TCX_TEAM_PROJECTS
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  UPDATE &&OWNER..TCX_CONFIG
     SET OBJECT_TIMESTAMP = SYSDATE
   WHERE CONFIG_ID = :NEW.CONFIG_ID;
END;
/


SET DEFINE ON
Prompt Granting SELECT, UPDATE on TCX_CONFIG to PUBLIC
GRANT SELECT, UPDATE ON &&OWNER..TCX_CONFIG TO "PUBLIC";


Prompt Granting SELECT on TCX_TEAM_PROJECTS to PUBLIC
GRANT SELECT ON &&OWNER..TCX_TEAM_PROJECTS TO "PUBLIC";


Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_OBJECTS to PUBLIC
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_OBJECTS TO "PUBLIC";


Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_OBJECT_HISTORY to PUBLIC
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_OBJECT_HISTORY TO "PUBLIC";


Prompt Granting SELECT on TCX_SCRIPT_SEQ to PUBLIC
GRANT SELECT ON &&OWNER..TCX_SCRIPT_SEQ TO "PUBLIC";



Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_CONFIG to &&TC_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_CONFIG TO "&&TC_ADMIN";


Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_TEAM_PROJECTS to &&TC_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_TEAM_PROJECTS TO "&&TC_ADMIN";


Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_OBJECTS to &&TC_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_OBJECTS TO "&&TC_ADMIN";


Prompt Granting SELECT, INSERT, UPDATE, DELETE on TCX_OBJECT_HISTORY to &&TC_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON &&OWNER..TCX_OBJECT_HISTORY TO "&&TC_ADMIN";


Prompt Granting SELECT on TCX_SCRIPT_SEQ to &&TC_ADMIN
GRANT SELECT ON &&OWNER..TCX_SCRIPT_SEQ TO "&&TC_ADMIN";


Prompt Creating public synonym: QUEST_TEAM_CODING
CREATE OR REPLACE PUBLIC SYNONYM QUEST_TEAM_CODING FOR &&OWNER..TCX_CONFIG;
Prompt Creating public synonym: DELL_COM_TEAM_CODING
CREATE OR REPLACE PUBLIC SYNONYM DELL_COM_TEAM_CODING FOR &&OWNER..TCX_CONFIG;
